name: test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: false
      - name: slangroom tests
        run: |
          ln -s `mise which slangroom-exec` bin/slangroom-exec
          make check
      - name: W3C VC journey
        run: |
          make
